### ISSUE TITLE
[Non-Vital] Explaing what this is (on thunderstore)

### ISSUE THREAD

**Issue by FrostyCirno** [Terraformer9x/RebalancedMineshaft#1]
How does it become more balanced compared to Factory and Mansion?

**Comment by Terraformer9x** [comment]
The mod functionally does a couple things to Mineshaft's generation.
- It reduces the generation length of Mineshaft by about half and readjusts the distribution and branch count of the dungeon's archetypes, you can look in Plugin.cs for specifics.
- It adds extra scrap spawn points to the grey tunnel tile pieces, such as on the shelves, pallets, and some of the mine-carts.
- It makes cave tiles unable to spawn "tabletop" loot and overall makes caves spawn less scrap, making loot distribution more even across the entire interior instead of it being heavy cave-focused.
- The mod also removes the 6 extra scrap spawn for Mineshafts as well as the Maneater's increased spawn chance on it, this will be made configurable later on.

Sorry for not elaborating on the Thunderstore page, I was in a hurry to upload last night.
